name: Test BlackArch Helper

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build/test in Arch container
        run: |
          docker run --rm -v $PWD:/app -w /app archlinux:base-devel bash -c "
            pacman -Sy --noconfirm archlinux-keyring base-devel fzf namcap sudo

            useradd -m builduser
            echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

            chown -R builduser:builduser /app

            sudo -u builduser bash -c '
              cd /app
              makepkg --nobuild
              namcap PKGBUILD || true
              chmod +x blackarch-helper
              ./blackarch-helper categories || true
            '

            echo 'Build completed.'
          "
